import { useParams, useNavigate } from 'react-router-dom'
import { useState, useEffect, useMemo } from 'react'
import { MOCK_CLIENTS } from '../data/mockData'
import { AuthUser, ClientFile } from '../types'
import Navbar from '../components/Navbar'
import FileUpload from '../components/FileUpload'
import DeviceCard from '../components/DeviceCard'
import SupportBlock from '../components/SupportBlock'
import { FileListSkeleton, ClientHeaderSkeleton } from '../components/Skeleton'
import { useToast } from '../context/ToastContext'

interface ClientFilesPageProps {
  user: AuthUser
  onLogout: () => void
}

const FILE_ICONS: Record<ClientFile['type'], JSX.Element> = {
  pdf: (
    <svg className="w-5 h-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
    </svg>
  ),
  archive: (
    <svg className="w-5 h-5 text-yellow-500" fill="currentColor" viewBox="0 0 20 20">
      <path d="M4 3a2 2 0 100 4h12a2 2 0 100-4H4z" />
      <path fillRule="evenodd" d="M3 8h14v7a2 2 0 01-2 2H5a2 2 0 01-2-2V8zm5 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" clipRule="evenodd" />
    </svg>
  ),
  image: (
    <svg className="w-5 h-5 text-green-500" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
    </svg>
  ),
  video: (
    <svg className="w-5 h-5 text-purple-500" fill="currentColor" viewBox="0 0 20 20">
      <path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zm12.553 1.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z" />
    </svg>
  ),
  document: (
    <svg className="w-5 h-5 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4z" clipRule="evenodd" />
    </svg>
  ),
}

function triggerDownload(filename: string) {
  const content = `Mock file: ${filename}\nGenerated by ${filename}\nDate: ${new Date().toISOString()}`
  const blob = new Blob([content], { type: 'application/octet-stream' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function getGreeting() {
  const hour = new Date().getHours()
  if (hour < 12) return 'Good morning'
  if (hour < 17) return 'Good afternoon'
  return 'Good evening'
}

function getDaysUntilExpiry(dateStr: string): number {
  return Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86400000)
}

function isNewFile(uploadedAt: string): boolean {
  return getDaysUntilExpiry(uploadedAt) > -14 && getDaysUntilExpiry(uploadedAt) <= 0
    ? false
    : Math.ceil((Date.now() - new Date(uploadedAt).getTime()) / 86400000) <= 14
}

export default function ClientFilesPage({ user, onLogout }: ClientFilesPageProps) {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { showToast } = useToast()
  const [loading, setLoading] = useState(true)
  const [downloading, setDownloading] = useState<string | null>(null)
  const [downloaded, setDownloaded] = useState<Set<string>>(new Set())
  const [activeCategory, setActiveCategory] = useState('All')
  const [activeDeviceId, setActiveDeviceId] = useState<string | null>(null)
  const [search, setSearch] = useState('')

  const viewableId = user.role === 'client' ? user.clientId : id
  const baseClient = MOCK_CLIENTS.find((c) => c.id === viewableId)
  const [extraFiles, setExtraFiles] = useState<ClientFile[]>([])

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 900)
    return () => clearTimeout(timer)
  }, [])

  if (user.role === 'client' && id !== user.clientId) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <p className="text-gray-500 font-medium">Access denied.</p>
          <button onClick={onLogout} className="mt-4 text-sm text-brand-600 hover:underline">Sign out</button>
        </div>
      </div>
    )
  }

  if (!baseClient) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <p className="text-gray-500">Client not found.</p>
      </div>
    )
  }

  const allFiles = [...baseClient.files, ...extraFiles]

  const filteredFiles = useMemo(() => {
    return allFiles.filter((f) => {
      const matchesDevice = activeDeviceId ? f.deviceId === activeDeviceId : true
      const matchesCategory = activeCategory === 'All' || f.category === activeCategory
      const matchesSearch = f.name.toLowerCase().includes(search.toLowerCase())
      return matchesDevice && matchesCategory && matchesSearch
    })
  }, [allFiles, activeDeviceId, activeCategory, search])

  const categories = ['All', ...Array.from(new Set(
    (activeDeviceId ? allFiles.filter(f => f.deviceId === activeDeviceId) : allFiles).map((f) => f.category)
  ))]

  function handleFilesAdded(files: ClientFile[]) {
    const withDevice = files.map(f => ({
      ...f,
      deviceId: activeDeviceId ?? baseClient!.devices[0]?.id ?? 'unknown',
    }))
    setExtraFiles((prev) => [...prev, ...withDevice])
    showToast(`${files.length} file${files.length > 1 ? 's' : ''} uploaded`, 'success')
    setActiveCategory('All')
  }

  async function handleDownload(file: ClientFile) {
    setDownloading(file.id)
    await new Promise((res) => setTimeout(res, 800))
    triggerDownload(file.name)
    setDownloading(null)
    setDownloaded((prev) => new Set(prev).add(file.id))
    showToast(`${file.name} downloaded`, 'success')
  }

  async function handleDownloadAll() {
    if (filteredFiles.length === 0) return
    showToast(`Downloading ${filteredFiles.length} files...`, 'info')
    for (const file of filteredFiles) {
      if (!downloaded.has(file.id)) await handleDownload(file)
    }
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar onLogout={onLogout} />

      <main className="max-w-6xl mx-auto px-6 py-10">
        {/* Back button — admin only */}
        {user.role === 'admin' && (
          <button
            onClick={() => navigate('/dashboard')}
            className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-900 mb-6 transition"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Clients
          </button>
        )}

        {/* Welcome banner — client only */}
        {user.role === 'client' && !loading && (
          <div className="mb-6 bg-gradient-to-r from-brand-700 to-brand-500 rounded-2xl px-6 py-5 text-white">
            <p className="text-sm text-brand-100 font-medium">{getGreeting()},</p>
            <h2 className="text-xl font-bold mt-0.5">{baseClient.name}</h2>
            <p className="text-brand-100 text-sm mt-1">
              {baseClient.company} &middot; {allFiles.length} files across {baseClient.devices.length} device{baseClient.devices.length !== 1 ? 's' : ''}
            </p>
          </div>
        )}

        {/* Client header */}
        {loading ? <ClientHeaderSkeleton /> : (
          <div className="bg-white rounded-2xl border border-gray-200 p-6 mb-6 flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-full bg-brand-100 text-brand-700 font-bold flex items-center justify-center text-base shrink-0">
                {baseClient.avatarInitials}
              </div>
              <div>
                <h2 className="text-xl font-bold text-gray-900">{baseClient.name}</h2>
                <p className="text-sm text-gray-500">{baseClient.company} &middot; {baseClient.email}</p>
              </div>
            </div>
            <button
              onClick={handleDownloadAll}
              className="flex items-center gap-2 bg-brand-600 hover:bg-brand-700 text-white text-sm font-semibold px-5 py-2.5 rounded-lg transition"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Download All
            </button>
          </div>
        )}

        {/* Device overview */}
        {!loading && (
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wide mb-3">Devices</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {baseClient.devices.map((device) => (
                <DeviceCard
                  key={device.id}
                  device={device}
                  files={allFiles.filter((f) => f.deviceId === device.id)}
                  isActive={activeDeviceId === device.id}
                  onClick={() => {
                    setActiveDeviceId(activeDeviceId === device.id ? null : device.id)
                    setActiveCategory('All')
                  }}
                />
              ))}
            </div>
          </div>
        )}

        {/* File upload — admin only */}
        {user.role === 'admin' && !loading && (
          <FileUpload onFilesAdded={handleFilesAdded} deviceId={activeDeviceId ?? ''} />
        )}

        {/* Search + category filters */}
        {!loading && (
          <div className="flex flex-col sm:flex-row gap-3 mb-5">
            <div className="relative flex-1">
              <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search files..."
                className="w-full pl-9 pr-4 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent bg-white"
              />
            </div>
            <div className="flex gap-2 overflow-x-auto pb-1 sm:flex-wrap sm:pb-0">
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
                    activeCategory === cat
                      ? 'bg-brand-600 text-white'
                      : 'bg-white border border-gray-200 text-gray-600 hover:border-brand-500 hover:text-brand-600'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Files list */}
        {loading ? <FileListSkeleton /> : (
          <div className="bg-white rounded-2xl border border-gray-200 divide-y divide-gray-100">
            {filteredFiles.length === 0 && (
              <div className="flex flex-col items-center py-16 text-center">
                <div className="w-14 h-14 bg-gray-100 rounded-full flex items-center justify-center mb-3">
                  <svg className="w-6 h-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                </div>
                <p className="text-gray-500 font-medium text-sm">No files found</p>
                <p className="text-gray-400 text-xs mt-1">Try adjusting your search or filters</p>
              </div>
            )}
            {filteredFiles.map((file) => {
              const isNew = isNewFile(file.uploadedAt)

              return (
                <div key={file.id} className="flex flex-col sm:flex-row sm:items-center justify-between px-4 sm:px-6 py-4 gap-3">
                  <div className="flex items-center gap-3 min-w-0 flex-1">
                    <div className="shrink-0">{FILE_ICONS[file.type]}</div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <p className="font-medium text-gray-900 truncate text-sm">{file.name}</p>
                        {isNew && (
                          <span className="text-xs font-semibold bg-brand-100 text-brand-700 px-2 py-0.5 rounded-full shrink-0">New</span>
                        )}
                        {file.version && (
                          <span className="text-xs font-mono bg-gray-100 text-gray-600 px-2 py-0.5 rounded shrink-0">{file.version}</span>
                        )}
                      </div>
                      <p className="text-xs text-gray-400 mt-0.5">
                        {file.size} &middot; {file.uploadedAt} &middot; {file.category}
                      </p>
                    </div>
                  </div>

                  <button
                    onClick={() => handleDownload(file)}
                    disabled={downloading === file.id}
                    className={`shrink-0 self-end sm:self-auto flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg transition ${
                      downloaded.has(file.id)
                        ? 'bg-green-50 text-green-600 border border-green-200'
                        : 'bg-gray-100 text-gray-700 hover:bg-brand-600 hover:text-white border border-transparent'
                    } disabled:opacity-50`}
                  >
                    {downloading === file.id ? (
                      <>
                        <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                        </svg>
                        Downloading
                      </>
                    ) : downloaded.has(file.id) ? (
                      <>
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                        Downloaded
                      </>
                    ) : (
                      <>
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                        Download
                      </>
                    )}
                  </button>
                </div>
              )
            })}
          </div>
        )}

        {/* Support block */}
        {!loading && <SupportBlock />}
      </main>
    </div>
  )
}
